# Generated by Django 5.0.6 on 2024-06-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='user_id',
        ),
    ]
