version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "stori_db_password"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
