version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "stori_db_password"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  flask_app:
    build:
      context: python_backend/services/authentication
      dockerfile: api.Dockerfile
    environment:
      SECRET_KEY: "my_super_secret_key"
      DATABASE_URL: "postgresql://postgres:stori_db_password@postgres:5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
