# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"A\n\x0eVerifyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05valid\x18\x02 \x01(\x08\x12\x0f\n\x07user_id\x18\x03 \x01(\t2A\n\x14\x41uthenticationServer\x12)\n\x06Verify\x12\x0e.VerifyRequest\x1a\x0f.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYREQUEST']._serialized_start=14
  _globals['_VERIFYREQUEST']._serialized_end=44
  _globals['_VERIFYRESPONSE']._serialized_start=46
  _globals['_VERIFYRESPONSE']._serialized_end=111
  _globals['_AUTHENTICATIONSERVER']._serialized_start=113
  _globals['_AUTHENTICATIONSERVER']._serialized_end=178
# @@protoc_insertion_point(module_scope)
